// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package hatoba provides the client and types for making API
// requests to NIFCLOUD Hatoba beta.
//
// See https://pfs.nifcloud.com/api//goto/WebAPI/hatoba-2019-03-27 for more information on this service.
//
// See hatoba package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/hatoba/
//
// Using the Client
//
// To NIFCLOUD Hatoba beta with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the NIFCLOUD Hatoba beta client Hatoba for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/hatoba/#New
package hatoba
