// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package hatoba

import (
	"github.com/alice02/nifcloud-sdk-go-v2/nifcloud"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/private/protocol/restjson"
)

// Hatoba provides the API operation methods for making requests to
// NIFCLOUD Hatoba beta. See this package's package overview docs
// for details on the service.
//
// Hatoba methods are safe to use concurrently. It is not safe to
// modify mutate any of the struct's properties though.
type Hatoba struct {
	*aws.Client
}

// Used for custom client initialization logic
var initClient func(*Hatoba)

// Used for custom request initialization logic
var initRequest func(*Hatoba, *aws.Request)

// Service information constants
const (
	ServiceName = "hatoba"    // Service endpoint prefix API calls made to.
	EndpointsID = ServiceName // Service ID for Regions and Endpoints metadata.
)

// New creates a new instance of the Hatoba client with a config.
//
// Example:
//     // Create a Hatoba client from just a config.
//     svc := hatoba.New(myConfig)
func New(config nifcloud.Config) *Hatoba {
	var signingName string
	signingRegion := config.Region

	svc := &Hatoba{
		Client: aws.NewClient(
			config.AWSConfig(),
			aws.Metadata{
				ServiceName:   ServiceName,
				SigningName:   signingName,
				SigningRegion: signingRegion,
				APIVersion:    "2019-03-27",
			},
		),
	}

	// Handlers
	svc.Handlers.Sign.PushBackNamed(v4.SignRequestHandler)
	svc.Handlers.Build.PushBackNamed(restjson.BuildHandler)
	svc.Handlers.Unmarshal.PushBackNamed(restjson.UnmarshalHandler)
	svc.Handlers.UnmarshalMeta.PushBackNamed(restjson.UnmarshalMetaHandler)
	svc.Handlers.UnmarshalError.PushBackNamed(restjson.UnmarshalErrorHandler)

	// Run custom client initialization if present
	if initClient != nil {
		initClient(svc)
	}

	return svc
}

// newRequest creates a new request for a Hatoba operation and runs any
// custom request initialization.
func (c *Hatoba) newRequest(op *aws.Operation, params, data interface{}) *aws.Request {
	req := c.NewRequest(op, params, data)

	// Run custom request initialization if present
	if initRequest != nil {
		initRequest(c, req)
	}

	return req
}
