// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package nas

import (
	"time"

	"github.com/alice02/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/private/protocol"
	"github.com/aws/aws-sdk-go-v2/private/protocol/query"
)

const opAuthorizeNASSecurityGroupIngress = "AuthorizeNASSecurityGroupIngress"

// AuthorizeNASSecurityGroupIngressRequest is a API request type for the AuthorizeNASSecurityGroupIngress API operation.
type AuthorizeNASSecurityGroupIngressRequest struct {
	*aws.Request
	Input *AuthorizeNASSecurityGroupIngressInput
	Copy  func(*AuthorizeNASSecurityGroupIngressInput) AuthorizeNASSecurityGroupIngressRequest
}

// Send marshals and sends the AuthorizeNASSecurityGroupIngress API request.
func (r AuthorizeNASSecurityGroupIngressRequest) Send() (*AuthorizeNASSecurityGroupIngressOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*AuthorizeNASSecurityGroupIngressOutput), nil
}

// AuthorizeNASSecurityGroupIngressRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the AuthorizeNASSecurityGroupIngressRequest method.
//    req := client.AuthorizeNASSecurityGroupIngressRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/AuthorizeNASSecurityGroupIngress
func (c *Nas) AuthorizeNASSecurityGroupIngressRequest(input *AuthorizeNASSecurityGroupIngressInput) AuthorizeNASSecurityGroupIngressRequest {
	op := &aws.Operation{
		Name:       opAuthorizeNASSecurityGroupIngress,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &AuthorizeNASSecurityGroupIngressInput{}
	}

	output := &AuthorizeNASSecurityGroupIngressOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return AuthorizeNASSecurityGroupIngressRequest{Request: req, Input: input, Copy: c.AuthorizeNASSecurityGroupIngressRequest}
}

const opCreateNASInstance = "CreateNASInstance"

// CreateNASInstanceRequest is a API request type for the CreateNASInstance API operation.
type CreateNASInstanceRequest struct {
	*aws.Request
	Input *CreateNASInstanceInput
	Copy  func(*CreateNASInstanceInput) CreateNASInstanceRequest
}

// Send marshals and sends the CreateNASInstance API request.
func (r CreateNASInstanceRequest) Send() (*CreateNASInstanceOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*CreateNASInstanceOutput), nil
}

// CreateNASInstanceRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the CreateNASInstanceRequest method.
//    req := client.CreateNASInstanceRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/CreateNASInstance
func (c *Nas) CreateNASInstanceRequest(input *CreateNASInstanceInput) CreateNASInstanceRequest {
	op := &aws.Operation{
		Name:       opCreateNASInstance,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateNASInstanceInput{}
	}

	output := &CreateNASInstanceOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return CreateNASInstanceRequest{Request: req, Input: input, Copy: c.CreateNASInstanceRequest}
}

const opCreateNASSecurityGroup = "CreateNASSecurityGroup"

// CreateNASSecurityGroupRequest is a API request type for the CreateNASSecurityGroup API operation.
type CreateNASSecurityGroupRequest struct {
	*aws.Request
	Input *CreateNASSecurityGroupInput
	Copy  func(*CreateNASSecurityGroupInput) CreateNASSecurityGroupRequest
}

// Send marshals and sends the CreateNASSecurityGroup API request.
func (r CreateNASSecurityGroupRequest) Send() (*CreateNASSecurityGroupOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*CreateNASSecurityGroupOutput), nil
}

// CreateNASSecurityGroupRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the CreateNASSecurityGroupRequest method.
//    req := client.CreateNASSecurityGroupRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/CreateNASSecurityGroup
func (c *Nas) CreateNASSecurityGroupRequest(input *CreateNASSecurityGroupInput) CreateNASSecurityGroupRequest {
	op := &aws.Operation{
		Name:       opCreateNASSecurityGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &CreateNASSecurityGroupInput{}
	}

	output := &CreateNASSecurityGroupOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return CreateNASSecurityGroupRequest{Request: req, Input: input, Copy: c.CreateNASSecurityGroupRequest}
}

const opDeleteNASInstance = "DeleteNASInstance"

// DeleteNASInstanceRequest is a API request type for the DeleteNASInstance API operation.
type DeleteNASInstanceRequest struct {
	*aws.Request
	Input *DeleteNASInstanceInput
	Copy  func(*DeleteNASInstanceInput) DeleteNASInstanceRequest
}

// Send marshals and sends the DeleteNASInstance API request.
func (r DeleteNASInstanceRequest) Send() (*DeleteNASInstanceOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*DeleteNASInstanceOutput), nil
}

// DeleteNASInstanceRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the DeleteNASInstanceRequest method.
//    req := client.DeleteNASInstanceRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DeleteNASInstance
func (c *Nas) DeleteNASInstanceRequest(input *DeleteNASInstanceInput) DeleteNASInstanceRequest {
	op := &aws.Operation{
		Name:       opDeleteNASInstance,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DeleteNASInstanceInput{}
	}

	output := &DeleteNASInstanceOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return DeleteNASInstanceRequest{Request: req, Input: input, Copy: c.DeleteNASInstanceRequest}
}

const opDeleteNASSecurityGroup = "DeleteNASSecurityGroup"

// DeleteNASSecurityGroupRequest is a API request type for the DeleteNASSecurityGroup API operation.
type DeleteNASSecurityGroupRequest struct {
	*aws.Request
	Input *DeleteNASSecurityGroupInput
	Copy  func(*DeleteNASSecurityGroupInput) DeleteNASSecurityGroupRequest
}

// Send marshals and sends the DeleteNASSecurityGroup API request.
func (r DeleteNASSecurityGroupRequest) Send() (*DeleteNASSecurityGroupOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*DeleteNASSecurityGroupOutput), nil
}

// DeleteNASSecurityGroupRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the DeleteNASSecurityGroupRequest method.
//    req := client.DeleteNASSecurityGroupRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DeleteNASSecurityGroup
func (c *Nas) DeleteNASSecurityGroupRequest(input *DeleteNASSecurityGroupInput) DeleteNASSecurityGroupRequest {
	op := &aws.Operation{
		Name:       opDeleteNASSecurityGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DeleteNASSecurityGroupInput{}
	}

	output := &DeleteNASSecurityGroupOutput{}
	req := c.newRequest(op, input, output)
	req.Handlers.Unmarshal.Remove(query.UnmarshalHandler)
	req.Handlers.Unmarshal.PushBackNamed(protocol.UnmarshalDiscardBodyHandler)
	output.responseMetadata = aws.Response{Request: req}

	return DeleteNASSecurityGroupRequest{Request: req, Input: input, Copy: c.DeleteNASSecurityGroupRequest}
}

const opDescribeNASInstances = "DescribeNASInstances"

// DescribeNASInstancesRequest is a API request type for the DescribeNASInstances API operation.
type DescribeNASInstancesRequest struct {
	*aws.Request
	Input *DescribeNASInstancesInput
	Copy  func(*DescribeNASInstancesInput) DescribeNASInstancesRequest
}

// Send marshals and sends the DescribeNASInstances API request.
func (r DescribeNASInstancesRequest) Send() (*DescribeNASInstancesOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*DescribeNASInstancesOutput), nil
}

// DescribeNASInstancesRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the DescribeNASInstancesRequest method.
//    req := client.DescribeNASInstancesRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DescribeNASInstances
func (c *Nas) DescribeNASInstancesRequest(input *DescribeNASInstancesInput) DescribeNASInstancesRequest {
	op := &aws.Operation{
		Name:       opDescribeNASInstances,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DescribeNASInstancesInput{}
	}

	output := &DescribeNASInstancesOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return DescribeNASInstancesRequest{Request: req, Input: input, Copy: c.DescribeNASInstancesRequest}
}

const opDescribeNASSecurityGroups = "DescribeNASSecurityGroups"

// DescribeNASSecurityGroupsRequest is a API request type for the DescribeNASSecurityGroups API operation.
type DescribeNASSecurityGroupsRequest struct {
	*aws.Request
	Input *DescribeNASSecurityGroupsInput
	Copy  func(*DescribeNASSecurityGroupsInput) DescribeNASSecurityGroupsRequest
}

// Send marshals and sends the DescribeNASSecurityGroups API request.
func (r DescribeNASSecurityGroupsRequest) Send() (*DescribeNASSecurityGroupsOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*DescribeNASSecurityGroupsOutput), nil
}

// DescribeNASSecurityGroupsRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the DescribeNASSecurityGroupsRequest method.
//    req := client.DescribeNASSecurityGroupsRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DescribeNASSecurityGroups
func (c *Nas) DescribeNASSecurityGroupsRequest(input *DescribeNASSecurityGroupsInput) DescribeNASSecurityGroupsRequest {
	op := &aws.Operation{
		Name:       opDescribeNASSecurityGroups,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &DescribeNASSecurityGroupsInput{}
	}

	output := &DescribeNASSecurityGroupsOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return DescribeNASSecurityGroupsRequest{Request: req, Input: input, Copy: c.DescribeNASSecurityGroupsRequest}
}

const opGetMetricStatistics = "GetMetricStatistics"

// GetMetricStatisticsRequest is a API request type for the GetMetricStatistics API operation.
type GetMetricStatisticsRequest struct {
	*aws.Request
	Input *GetMetricStatisticsInput
	Copy  func(*GetMetricStatisticsInput) GetMetricStatisticsRequest
}

// Send marshals and sends the GetMetricStatistics API request.
func (r GetMetricStatisticsRequest) Send() (*GetMetricStatisticsOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*GetMetricStatisticsOutput), nil
}

// GetMetricStatisticsRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the GetMetricStatisticsRequest method.
//    req := client.GetMetricStatisticsRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/GetMetricStatistics
func (c *Nas) GetMetricStatisticsRequest(input *GetMetricStatisticsInput) GetMetricStatisticsRequest {
	op := &aws.Operation{
		Name:       opGetMetricStatistics,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &GetMetricStatisticsInput{}
	}

	output := &GetMetricStatisticsOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return GetMetricStatisticsRequest{Request: req, Input: input, Copy: c.GetMetricStatisticsRequest}
}

const opModifyNASInstance = "ModifyNASInstance"

// ModifyNASInstanceRequest is a API request type for the ModifyNASInstance API operation.
type ModifyNASInstanceRequest struct {
	*aws.Request
	Input *ModifyNASInstanceInput
	Copy  func(*ModifyNASInstanceInput) ModifyNASInstanceRequest
}

// Send marshals and sends the ModifyNASInstance API request.
func (r ModifyNASInstanceRequest) Send() (*ModifyNASInstanceOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*ModifyNASInstanceOutput), nil
}

// ModifyNASInstanceRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the ModifyNASInstanceRequest method.
//    req := client.ModifyNASInstanceRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/ModifyNASInstance
func (c *Nas) ModifyNASInstanceRequest(input *ModifyNASInstanceInput) ModifyNASInstanceRequest {
	op := &aws.Operation{
		Name:       opModifyNASInstance,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ModifyNASInstanceInput{}
	}

	output := &ModifyNASInstanceOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return ModifyNASInstanceRequest{Request: req, Input: input, Copy: c.ModifyNASInstanceRequest}
}

const opModifyNASSecurityGroup = "ModifyNASSecurityGroup"

// ModifyNASSecurityGroupRequest is a API request type for the ModifyNASSecurityGroup API operation.
type ModifyNASSecurityGroupRequest struct {
	*aws.Request
	Input *ModifyNASSecurityGroupInput
	Copy  func(*ModifyNASSecurityGroupInput) ModifyNASSecurityGroupRequest
}

// Send marshals and sends the ModifyNASSecurityGroup API request.
func (r ModifyNASSecurityGroupRequest) Send() (*ModifyNASSecurityGroupOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*ModifyNASSecurityGroupOutput), nil
}

// ModifyNASSecurityGroupRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the ModifyNASSecurityGroupRequest method.
//    req := client.ModifyNASSecurityGroupRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/ModifyNASSecurityGroup
func (c *Nas) ModifyNASSecurityGroupRequest(input *ModifyNASSecurityGroupInput) ModifyNASSecurityGroupRequest {
	op := &aws.Operation{
		Name:       opModifyNASSecurityGroup,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ModifyNASSecurityGroupInput{}
	}

	output := &ModifyNASSecurityGroupOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return ModifyNASSecurityGroupRequest{Request: req, Input: input, Copy: c.ModifyNASSecurityGroupRequest}
}

const opRevokeNASSecurityGroupIngress = "RevokeNASSecurityGroupIngress"

// RevokeNASSecurityGroupIngressRequest is a API request type for the RevokeNASSecurityGroupIngress API operation.
type RevokeNASSecurityGroupIngressRequest struct {
	*aws.Request
	Input *RevokeNASSecurityGroupIngressInput
	Copy  func(*RevokeNASSecurityGroupIngressInput) RevokeNASSecurityGroupIngressRequest
}

// Send marshals and sends the RevokeNASSecurityGroupIngress API request.
func (r RevokeNASSecurityGroupIngressRequest) Send() (*RevokeNASSecurityGroupIngressOutput, error) {
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*RevokeNASSecurityGroupIngressOutput), nil
}

// RevokeNASSecurityGroupIngressRequest returns a request value for making API operation for
// NIFCLOUD NAS.
//
//    // Example sending a request using the RevokeNASSecurityGroupIngressRequest method.
//    req := client.RevokeNASSecurityGroupIngressRequest(params)
//    resp, err := req.Send()
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/RevokeNASSecurityGroupIngress
func (c *Nas) RevokeNASSecurityGroupIngressRequest(input *RevokeNASSecurityGroupIngressInput) RevokeNASSecurityGroupIngressRequest {
	op := &aws.Operation{
		Name:       opRevokeNASSecurityGroupIngress,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &RevokeNASSecurityGroupIngressInput{}
	}

	output := &RevokeNASSecurityGroupIngressOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return RevokeNASSecurityGroupIngressRequest{Request: req, Input: input, Copy: c.RevokeNASSecurityGroupIngressRequest}
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/AuthorizeNASSecurityGroupIngressRequest
type AuthorizeNASSecurityGroupIngressInput struct {
	_ struct{} `type:"structure"`

	CIDRIP *string `locationName:"CIDRIP" type:"string"`

	NASSecurityGroupName *string `locationName:"NASSecurityGroupName" type:"string"`

	SecurityGroupName *string `locationName:"SecurityGroupName" type:"string"`
}

// String returns the string representation
func (s AuthorizeNASSecurityGroupIngressInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s AuthorizeNASSecurityGroupIngressInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/AuthorizeNASSecurityGroupIngressResult
type AuthorizeNASSecurityGroupIngressOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASSecurityGroup *NASSecurityGroup `type:"structure"`
}

// String returns the string representation
func (s AuthorizeNASSecurityGroupIngressOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s AuthorizeNASSecurityGroupIngressOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s AuthorizeNASSecurityGroupIngressOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/CreateNASInstanceRequest
type CreateNASInstanceInput struct {
	_ struct{} `type:"structure"`

	AllocatedStorage *int64 `locationName:"AllocatedStorage" type:"integer"`

	AvailabilityZone *string `locationName:"AvailabilityZone" type:"string"`

	MasterPrivateAddress *string `locationName:"MasterPrivateAddress" type:"string"`

	MasterUserPassword *string `locationName:"MasterUserPassword" type:"string"`

	MasterUsername *string `locationName:"MasterUsername" type:"string"`

	NASInstanceDescription *string `locationName:"NASInstanceDescription" type:"string"`

	NASInstanceIdentifier *string `locationName:"NASInstanceIdentifier" type:"string"`

	NASInstanceType *int64 `locationName:"NASInstanceType" type:"integer"`

	NASSecurityGroups []string `locationName:"NASSecurityGroups" locationNameList:"member" type:"list"`

	NetworkId *string `locationName:"NetworkId" type:"string"`

	Protocol *string `locationName:"Protocol" type:"string"`
}

// String returns the string representation
func (s CreateNASInstanceInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateNASInstanceInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/CreateNASInstanceResult
type CreateNASInstanceOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASInstance *NASInstance `type:"structure"`
}

// String returns the string representation
func (s CreateNASInstanceOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateNASInstanceOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s CreateNASInstanceOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/CreateNASSecurityGroupRequest
type CreateNASSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	AvailabilityZone *string `locationName:"AvailabilityZone" type:"string"`

	NASSecurityGroupDescription *string `locationName:"NASSecurityGroupDescription" type:"string"`

	NASSecurityGroupName *string `locationName:"NASSecurityGroupName" type:"string"`
}

// String returns the string representation
func (s CreateNASSecurityGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateNASSecurityGroupInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/CreateNASSecurityGroupResult
type CreateNASSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASSecurityGroup *NASSecurityGroup `type:"structure"`
}

// String returns the string representation
func (s CreateNASSecurityGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s CreateNASSecurityGroupOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s CreateNASSecurityGroupOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DeleteNASInstanceRequest
type DeleteNASInstanceInput struct {
	_ struct{} `type:"structure"`

	DirectoryServiceAdministratorName *string `locationName:"DirectoryServiceAdministratorName" type:"string"`

	DirectoryServiceAdministratorPassword *string `locationName:"DirectoryServiceAdministratorPassword" type:"string"`

	NASInstanceIdentifier *string `locationName:"NASInstanceIdentifier" type:"string"`
}

// String returns the string representation
func (s DeleteNASInstanceInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteNASInstanceInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DeleteNASInstanceResult
type DeleteNASInstanceOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASInstance *NASInstance `type:"structure"`
}

// String returns the string representation
func (s DeleteNASInstanceOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteNASInstanceOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s DeleteNASInstanceOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DeleteNASSecurityGroupRequest
type DeleteNASSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	NASSecurityGroupName *string `locationName:"NASSecurityGroupName" type:"string"`
}

// String returns the string representation
func (s DeleteNASSecurityGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteNASSecurityGroupInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DeleteNASSecurityGroupOutput
type DeleteNASSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response
}

// String returns the string representation
func (s DeleteNASSecurityGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DeleteNASSecurityGroupOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s DeleteNASSecurityGroupOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DescribeNASInstancesRequest
type DescribeNASInstancesInput struct {
	_ struct{} `type:"structure"`

	NASInstanceIdentifier *string `locationName:"NASInstanceIdentifier" type:"string"`
}

// String returns the string representation
func (s DescribeNASInstancesInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeNASInstancesInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DescribeNASInstancesResult
type DescribeNASInstancesOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASInstances []NASInstance `locationNameList:"NASInstance" type:"list"`
}

// String returns the string representation
func (s DescribeNASInstancesOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeNASInstancesOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s DescribeNASInstancesOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DescribeNASSecurityGroupsRequest
type DescribeNASSecurityGroupsInput struct {
	_ struct{} `type:"structure"`

	NASSecurityGroupName *string `locationName:"NASSecurityGroupName" type:"string"`
}

// String returns the string representation
func (s DescribeNASSecurityGroupsInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeNASSecurityGroupsInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DescribeNASSecurityGroupsResult
type DescribeNASSecurityGroupsOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASSecurityGroups []NASSecurityGroup `locationNameList:"NASSecurityGroup" type:"list"`
}

// String returns the string representation
func (s DescribeNASSecurityGroupsOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DescribeNASSecurityGroupsOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s DescribeNASSecurityGroupsOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/DomainController
type DomainController struct {
	_ struct{} `type:"structure"`

	Hostname *string `type:"string"`

	IPAddress *string `type:"string"`
}

// String returns the string representation
func (s DomainController) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s DomainController) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/Endpoint
type Endpoint struct {
	_ struct{} `type:"structure"`

	Address *string `type:"string"`

	PrivateAddress *string `type:"string"`
}

// String returns the string representation
func (s Endpoint) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s Endpoint) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/GetMetricStatisticsRequest
type GetMetricStatisticsInput struct {
	_ struct{} `type:"structure"`

	Dimensions []RequestDimensionsStruct `locationName:"Dimensions" locationNameList:"member" type:"list"`

	EndTime *time.Time `locationName:"EndTime" type:"timestamp" timestampFormat:"iso8601"`

	MetricName *string `locationName:"MetricName" type:"string"`

	StartTime *time.Time `locationName:"StartTime" type:"timestamp" timestampFormat:"iso8601"`
}

// String returns the string representation
func (s GetMetricStatisticsInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s GetMetricStatisticsInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/GetMetricStatisticsResult
type GetMetricStatisticsOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	Datapoints []Member `locationNameList:"member" type:"list"`

	Label *string `type:"string"`
}

// String returns the string representation
func (s GetMetricStatisticsOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s GetMetricStatisticsOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s GetMetricStatisticsOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/IPRange
type IPRange struct {
	_ struct{} `type:"structure"`

	CIDRIP *string `type:"string"`

	Status *string `type:"string"`
}

// String returns the string representation
func (s IPRange) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s IPRange) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/Member
type Member struct {
	_ struct{} `type:"structure"`

	SampleCount *string `type:"string"`

	Sum *string `type:"string"`

	TargetName *string `type:"string"`

	Timestamp *string `type:"string"`
}

// String returns the string representation
func (s Member) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s Member) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/ModifyNASInstanceRequest
type ModifyNASInstanceInput struct {
	_ struct{} `type:"structure"`

	AllocatedStorage *int64 `locationName:"AllocatedStorage" type:"integer"`

	AuthenticationType *int64 `locationName:"AuthenticationType" type:"integer"`

	DirectoryServiceAdministratorName *string `locationName:"DirectoryServiceAdministratorName" type:"string"`

	DirectoryServiceAdministratorPassword *string `locationName:"DirectoryServiceAdministratorPassword" type:"string"`

	DirectoryServiceDomainName *string `locationName:"DirectoryServiceDomainName" type:"string"`

	DomainControllers []RequestDomainControllersStruct `locationName:"DomainControllers" locationNameList:"member" type:"list"`

	MasterPrivateAddress *string `locationName:"MasterPrivateAddress" type:"string"`

	MasterUserPassword *string `locationName:"MasterUserPassword" type:"string"`

	NASInstanceDescription *string `locationName:"NASInstanceDescription" type:"string"`

	NASInstanceIdentifier *string `locationName:"NASInstanceIdentifier" type:"string"`

	NASSecurityGroups []string `locationName:"NASSecurityGroups" locationNameList:"member" type:"list"`

	NetworkId *string `locationName:"NetworkId" type:"string"`

	NewNASInstanceIdentifier *string `locationName:"NewNASInstanceIdentifier" type:"string"`
}

// String returns the string representation
func (s ModifyNASInstanceInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s ModifyNASInstanceInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/ModifyNASInstanceResult
type ModifyNASInstanceOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASInstance *NASInstance `type:"structure"`
}

// String returns the string representation
func (s ModifyNASInstanceOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s ModifyNASInstanceOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s ModifyNASInstanceOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/ModifyNASSecurityGroupRequest
type ModifyNASSecurityGroupInput struct {
	_ struct{} `type:"structure"`

	NASSecurityGroupDescription *string `locationName:"NASSecurityGroupDescription" type:"string"`

	NASSecurityGroupName *string `locationName:"NASSecurityGroupName" type:"string"`

	NewNASSecurityGroupName *string `locationName:"NewNASSecurityGroupName" type:"string"`
}

// String returns the string representation
func (s ModifyNASSecurityGroupInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s ModifyNASSecurityGroupInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/ModifyNASSecurityGroupResult
type ModifyNASSecurityGroupOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASSecurityGroup *NASSecurityGroup `type:"structure"`
}

// String returns the string representation
func (s ModifyNASSecurityGroupOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s ModifyNASSecurityGroupOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s ModifyNASSecurityGroupOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/NASInstance
type NASInstance struct {
	_ struct{} `type:"structure"`

	AllocatedStorage *string `type:"string"`

	AuthenticationType *int64 `type:"integer"`

	AvailabilityZone *string `type:"string"`

	CreateTime *string `type:"string"`

	DirectoryServiceDomainName *string `type:"string"`

	DomainControllers []DomainController `locationNameList:"DomainController" type:"list"`

	Endpoint *Endpoint `type:"structure"`

	MasterUsername *string `type:"string"`

	NASInstanceClass *string `type:"string"`

	NASInstanceDescription *string `type:"string"`

	NASInstanceErrorInfo *NASInstanceErrorInfo `type:"structure"`

	NASInstanceIdentifier *string `type:"string"`

	NASInstanceStatus *string `type:"string"`

	NASInstanceType *int64 `type:"integer"`

	NASSecurityGroups []NASSecurityGroup `locationNameList:"NASSecurityGroup" type:"list"`

	NetworkId *string `type:"string"`

	NoRootSquash *string `type:"string"`

	Protocol *string `type:"string"`

	StorageType *int64 `type:"integer"`
}

// String returns the string representation
func (s NASInstance) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s NASInstance) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/NASInstanceErrorInfo
type NASInstanceErrorInfo struct {
	_ struct{} `type:"structure"`

	NASInstanceErrorCode *string `type:"string"`

	NASInstanceErrorMessage *string `type:"string"`
}

// String returns the string representation
func (s NASInstanceErrorInfo) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s NASInstanceErrorInfo) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/NASSecurityGroup
type NASSecurityGroup struct {
	_ struct{} `type:"structure"`

	AvailabilityZone *string `type:"string"`

	IPRanges []IPRange `locationNameList:"IPRange" type:"list"`

	NASSecurityGroupDescription *string `type:"string"`

	NASSecurityGroupName *string `type:"string"`

	OwnerId *string `type:"string"`

	SecurityGroups []SecurityGroup `locationNameList:"SecurityGroup" type:"list"`
}

// String returns the string representation
func (s NASSecurityGroup) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s NASSecurityGroup) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/RequestDimensionsStruct
type RequestDimensionsStruct struct {
	_ struct{} `type:"structure"`

	Name *string `locationName:"Name" type:"string"`

	Value *string `locationName:"Value" type:"string"`
}

// String returns the string representation
func (s RequestDimensionsStruct) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s RequestDimensionsStruct) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/RequestDomainControllersStruct
type RequestDomainControllersStruct struct {
	_ struct{} `type:"structure"`

	Hostname *string `locationName:"Hostname" type:"string"`

	IPAddress *string `locationName:"IPAddress" type:"string"`
}

// String returns the string representation
func (s RequestDomainControllersStruct) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s RequestDomainControllersStruct) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/RevokeNASSecurityGroupIngressRequest
type RevokeNASSecurityGroupIngressInput struct {
	_ struct{} `type:"structure"`

	CIDRIP *string `locationName:"CIDRIP" type:"string"`

	NASSecurityGroupName *string `locationName:"NASSecurityGroupName" type:"string"`

	SecurityGroupName *string `locationName:"SecurityGroupName" type:"string"`
}

// String returns the string representation
func (s RevokeNASSecurityGroupIngressInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s RevokeNASSecurityGroupIngressInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/RevokeNASSecurityGroupIngressResult
type RevokeNASSecurityGroupIngressOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	NASSecurityGroup *NASSecurityGroup `type:"structure"`
}

// String returns the string representation
func (s RevokeNASSecurityGroupIngressOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s RevokeNASSecurityGroupIngressOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s RevokeNASSecurityGroupIngressOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/nas-N2016-02-24/SecurityGroup
type SecurityGroup struct {
	_ struct{} `type:"structure"`

	SecurityGroupName *string `type:"string"`

	SecurityGroupOwnerId *string `type:"string"`

	Status *string `type:"string"`
}

// String returns the string representation
func (s SecurityGroup) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s SecurityGroup) GoString() string {
	return s.String()
}
