// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package nas

import (
	"github.com/alice02/nifcloud-sdk-go-v2/nifcloud"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/private/protocol/query"
)

// Nas provides the API operation methods for making requests to
// NIFCLOUD NAS. See this package's package overview docs
// for details on the service.
//
// Nas methods are safe to use concurrently. It is not safe to
// modify mutate any of the struct's properties though.
type Nas struct {
	*aws.Client
}

// Used for custom client initialization logic
var initClient func(*Nas)

// Used for custom request initialization logic
var initRequest func(*Nas, *aws.Request)

// Service information constants
const (
	ServiceName = "nas"       // Service endpoint prefix API calls made to.
	EndpointsID = ServiceName // Service ID for Regions and Endpoints metadata.
)

// New creates a new instance of the Nas client with a config.
//
// Example:
//     // Create a Nas client from just a config.
//     svc := nas.New(myConfig)
func New(config nifcloud.Config) *Nas {
	var signingName string
	signingRegion := config.Region

	svc := &Nas{
		Client: aws.NewClient(
			config.AWSConfig(),
			aws.Metadata{
				ServiceName:   ServiceName,
				SigningName:   signingName,
				SigningRegion: signingRegion,
				APIVersion:    "N2016-02-24",
			},
		),
	}

	// Handlers
	svc.Handlers.Sign.PushBackNamed(v4.SignRequestHandler)
	svc.Handlers.Build.PushBackNamed(query.BuildHandler)
	svc.Handlers.Unmarshal.PushBackNamed(query.UnmarshalHandler)
	svc.Handlers.UnmarshalMeta.PushBackNamed(query.UnmarshalMetaHandler)
	svc.Handlers.UnmarshalError.PushBackNamed(query.UnmarshalErrorHandler)

	// Run custom client initialization if present
	if initClient != nil {
		initClient(svc)
	}

	return svc
}

// newRequest creates a new request for a Nas operation and runs any
// custom request initialization.
func (c *Nas) newRequest(op *aws.Operation, params, data interface{}) *aws.Request {
	req := c.NewRequest(op, params, data)

	// Run custom request initialization if present
	if initRequest != nil {
		initRequest(c, req)
	}

	return req
}
