// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package script

import (
	"context"

	"github.com/alice02/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

const opExecuteScript = "ExecuteScript"

// ExecuteScriptRequest is a API request type for the ExecuteScript API operation.
type ExecuteScriptRequest struct {
	*aws.Request
	Input *ExecuteScriptInput
	Copy  func(*ExecuteScriptInput) ExecuteScriptRequest
}

// Send marshals and sends the ExecuteScript API request.
func (r ExecuteScriptRequest) Send(ctx context.Context) (*ExecuteScriptOutput, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	return r.Request.Data.(*ExecuteScriptOutput), nil
}

// ExecuteScriptRequest returns a request value for making API operation for
// NIFCLOUD Script.
//
//    // Example sending a request using the ExecuteScriptRequest method.
//    req := client.ExecuteScriptRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/script-2015-09-01/ExecuteScript
func (c *Script) ExecuteScriptRequest(input *ExecuteScriptInput) ExecuteScriptRequest {
	op := &aws.Operation{
		Name:       opExecuteScript,
		HTTPMethod: "POST",
		HTTPPath:   "/2015-09-01/",
	}

	if input == nil {
		input = &ExecuteScriptInput{}
	}

	output := &ExecuteScriptOutput{}
	req := c.newRequest(op, input, output)
	output.responseMetadata = aws.Response{Request: req}

	return ExecuteScriptRequest{Request: req, Input: input, Copy: c.ExecuteScriptRequest}
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/script-2015-09-01/ExecuteScriptRequest
type ExecuteScriptInput struct {
	_ struct{} `type:"structure"`

	Body *string `locationName:"Body" type:"string"`

	Header *string `locationName:"Header" type:"string"`

	Method *string `locationName:"Method" type:"string"`

	Query *string `locationName:"Query" type:"string"`

	ScriptIdentifier *string `locationName:"ScriptIdentifier" type:"string"`
}

// String returns the string representation
func (s ExecuteScriptInput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s ExecuteScriptInput) GoString() string {
	return s.String()
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/script-2015-09-01/ExecuteScriptResult
type ExecuteScriptOutput struct {
	_ struct{} `type:"structure"`

	responseMetadata aws.Response

	Result *Result `type:"structure"`
}

// String returns the string representation
func (s ExecuteScriptOutput) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s ExecuteScriptOutput) GoString() string {
	return s.String()
}

// SDKResponseMetdata return sthe response metadata for the API.
func (s ExecuteScriptOutput) SDKResponseMetadata() aws.Response {
	return s.responseMetadata
}

// Please also see https://pfs.nifcloud.com/api//goto/WebAPI/script-2015-09-01/Result
type Result struct {
	_ struct{} `type:"structure"`

	RequestBody *string `type:"string"`

	RequestHeader *string `type:"string"`

	RequestQuery *string `type:"string"`

	ResponseData *string `type:"string"`

	ResponseHeader *string `type:"string"`

	ResponseStatus *int64 `type:"integer"`

	ScriptIdentifier *string `type:"string"`
}

// String returns the string representation
func (s Result) String() string {
	return nifcloudutil.Prettify(s)
}

// GoString returns the string representation
func (s Result) GoString() string {
	return s.String()
}
