// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package script

import (
	"github.com/alice02/nifcloud-sdk-go-v2/nifcloud"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/private/protocol/script"
)

// Script provides the API operation methods for making requests to
// NIFCLOUD Script. See this package's package overview docs
// for details on the service.
//
// Script methods are safe to use concurrently. It is not safe to
// modify mutate any of the struct's properties though.
type Script struct {
	*aws.Client
}

// Used for custom client initialization logic
var initClient func(*Script)

// Used for custom request initialization logic
var initRequest func(*Script, *aws.Request)

// Service information constants
const (
	ServiceName = "script"    // Service endpoint prefix API calls made to.
	EndpointsID = ServiceName // Service ID for Regions and Endpoints metadata.
)

// New creates a new instance of the Script client with a config.
//
// Example:
//     // Create a Script client from just a config.
//     svc := script.New(myConfig)
func New(config nifcloud.Config) *Script {
	var signingName string
	signingRegion := config.Region

	svc := &Script{
		Client: aws.NewClient(
			config.AWSConfig(),
			aws.Metadata{
				ServiceName:   ServiceName,
				SigningName:   signingName,
				SigningRegion: signingRegion,
				APIVersion:    "2015-09-01",

				TargetPrefix: "2015-09-01",
			},
		),
	}

	// Handlers
	svc.Handlers.Sign.PushBackNamed(v4.SignRequestHandler)
	svc.Handlers.Build.PushBackNamed(script.BuildHandler)
	svc.Handlers.Unmarshal.PushBackNamed(script.UnmarshalHandler)
	svc.Handlers.UnmarshalMeta.PushBackNamed(script.UnmarshalMetaHandler)
	svc.Handlers.UnmarshalError.PushBackNamed(script.UnmarshalErrorHandler)

	// Run custom client initialization if present
	if initClient != nil {
		initClient(svc)
	}

	return svc
}

// newRequest creates a new request for a Script operation and runs any
// custom request initialization.
func (c *Script) newRequest(op *aws.Operation, params, data interface{}) *aws.Request {
	req := c.NewRequest(op, params, data)

	// Run custom request initialization if present
	if initRequest != nil {
		initRequest(c, req)
	}

	return req
}
