// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package rdb

import (
	"context"

	"github.com/alice02/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type ModifyDBInstanceInput struct {
	_ struct{} `type:"structure"`

	AllocatedStorage *int64 `locationName:"AllocatedStorage" type:"integer"`

	ApplyImmediately *bool `locationName:"ApplyImmediately" type:"boolean"`

	BackupRetentionPeriod *int64 `locationName:"BackupRetentionPeriod" type:"integer"`

	BinlogRetentionPeriod *int64 `locationName:"BinlogRetentionPeriod" type:"integer"`

	CACertificateIdentifier *string `locationName:"CACertificateIdentifier" type:"string"`

	CustomBinlogRetentionPeriod *int64 `locationName:"CustomBinlogRetentionPeriod" type:"integer"`

	DBInstanceClass *string `locationName:"DBInstanceClass" type:"string"`

	DBInstanceIdentifier *string `locationName:"DBInstanceIdentifier" type:"string"`

	DBParameterGroupName *string `locationName:"DBParameterGroupName" type:"string"`

	DBSecurityGroups []string `locationName:"DBSecurityGroups" locationNameList:"member" type:"list"`

	MasterUserPassword *string `locationName:"MasterUserPassword" type:"string"`

	MultiAZ *bool `locationName:"MultiAZ" type:"boolean"`

	NewDBInstanceIdentifier *string `locationName:"NewDBInstanceIdentifier" type:"string"`

	NiftyMultiAZType *int64 `locationName:"NiftyMultiAZType" type:"integer"`

	NiftyReadReplicaDBInstanceIdentifier *string `locationName:"NiftyReadReplicaDBInstanceIdentifier" type:"string"`

	NiftyReadReplicaPrivateAddress *string `locationName:"NiftyReadReplicaPrivateAddress" type:"string"`

	NiftySlavePrivateAddress *string `locationName:"NiftySlavePrivateAddress" type:"string"`

	PreferredBackupWindow *string `locationName:"PreferredBackupWindow" type:"string"`

	PreferredMaintenanceWindow *string `locationName:"PreferredMaintenanceWindow" type:"string"`
}

// String returns the string representation
func (s ModifyDBInstanceInput) String() string {
	return nifcloudutil.Prettify(s)
}

type ModifyDBInstanceOutput struct {
	_ struct{} `type:"structure"`

	DBInstance *DBInstance `type:"structure"`
}

// String returns the string representation
func (s ModifyDBInstanceOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opModifyDBInstance = "ModifyDBInstance"

// ModifyDBInstanceRequest returns a request value for making API operation for
// NIFCLOUD RDB.
//
//    // Example sending a request using ModifyDBInstanceRequest.
//    req := client.ModifyDBInstanceRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/rdb-2013-05-15N2013-12-16/ModifyDBInstance
func (c *Client) ModifyDBInstanceRequest(input *ModifyDBInstanceInput) ModifyDBInstanceRequest {
	op := &aws.Operation{
		Name:       opModifyDBInstance,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &ModifyDBInstanceInput{}
	}

	req := c.newRequest(op, input, &ModifyDBInstanceOutput{})
	return ModifyDBInstanceRequest{Request: req, Input: input, Copy: c.ModifyDBInstanceRequest}
}

// ModifyDBInstanceRequest is the request type for the
// ModifyDBInstance API operation.
type ModifyDBInstanceRequest struct {
	*aws.Request
	Input *ModifyDBInstanceInput
	Copy  func(*ModifyDBInstanceInput) ModifyDBInstanceRequest
}

// Send marshals and sends the ModifyDBInstance API request.
func (r ModifyDBInstanceRequest) Send(ctx context.Context) (*ModifyDBInstanceResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ModifyDBInstanceResponse{
		ModifyDBInstanceOutput: r.Request.Data.(*ModifyDBInstanceOutput),
		response:               &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ModifyDBInstanceResponse is the response type for the
// ModifyDBInstance API operation.
type ModifyDBInstanceResponse struct {
	*ModifyDBInstanceOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ModifyDBInstance request.
func (r *ModifyDBInstanceResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
