// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type SetFilterForLoadBalancerInput struct {
	_ struct{} `type:"structure"`

	FilterType *string `locationName:"FilterType" type:"string"`

	IPAddresses []RequestIPAddressesStruct `locationName:"IPAddresses" locationNameList:"member" type:"list"`

	InstancePort *int64 `locationName:"InstancePort" type:"integer"`

	LoadBalancerName *string `locationName:"LoadBalancerName" type:"string"`

	LoadBalancerPort *int64 `locationName:"LoadBalancerPort" type:"integer"`
}

// String returns the string representation
func (s SetFilterForLoadBalancerInput) String() string {
	return nifcloudutil.Prettify(s)
}

type SetFilterForLoadBalancerOutput struct {
	_ struct{} `type:"structure"`

	Filter *Filter `locationName:"Filter" type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`

	SetFilterForLoadBalancerResult *SetFilterForLoadBalancerResult `locationName:"SetFilterForLoadBalancerResult" type:"structure"`
}

// String returns the string representation
func (s SetFilterForLoadBalancerOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opSetFilterForLoadBalancer = "SetFilterForLoadBalancer"

// SetFilterForLoadBalancerRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using SetFilterForLoadBalancerRequest.
//    req := client.SetFilterForLoadBalancerRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/SetFilterForLoadBalancer
func (c *Client) SetFilterForLoadBalancerRequest(input *SetFilterForLoadBalancerInput) SetFilterForLoadBalancerRequest {
	op := &aws.Operation{
		Name:       opSetFilterForLoadBalancer,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &SetFilterForLoadBalancerInput{}
	}

	req := c.newRequest(op, input, &SetFilterForLoadBalancerOutput{})
	return SetFilterForLoadBalancerRequest{Request: req, Input: input, Copy: c.SetFilterForLoadBalancerRequest}
}

// SetFilterForLoadBalancerRequest is the request type for the
// SetFilterForLoadBalancer API operation.
type SetFilterForLoadBalancerRequest struct {
	*aws.Request
	Input *SetFilterForLoadBalancerInput
	Copy  func(*SetFilterForLoadBalancerInput) SetFilterForLoadBalancerRequest
}

// Send marshals and sends the SetFilterForLoadBalancer API request.
func (r SetFilterForLoadBalancerRequest) Send(ctx context.Context) (*SetFilterForLoadBalancerResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &SetFilterForLoadBalancerResponse{
		SetFilterForLoadBalancerOutput: r.Request.Data.(*SetFilterForLoadBalancerOutput),
		response:                       &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// SetFilterForLoadBalancerResponse is the response type for the
// SetFilterForLoadBalancer API operation.
type SetFilterForLoadBalancerResponse struct {
	*SetFilterForLoadBalancerOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// SetFilterForLoadBalancer request.
func (r *SetFilterForLoadBalancerResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
