// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/alice02/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type NiftyRegisterInstancesWithElasticLoadBalancerInput struct {
	_ struct{} `type:"structure"`

	ElasticLoadBalancerId *string `locationName:"ElasticLoadBalancerId" type:"string"`

	ElasticLoadBalancerName *string `locationName:"ElasticLoadBalancerName" type:"string"`

	ElasticLoadBalancerPort *int64 `locationName:"ElasticLoadBalancerPort" type:"integer"`

	InstancePort *int64 `locationName:"InstancePort" type:"integer"`

	Instances []RequestInstancesStruct `locationName:"Instances" locationNameList:"member" type:"list"`

	Protocol *string `locationName:"Protocol" type:"string"`
}

// String returns the string representation
func (s NiftyRegisterInstancesWithElasticLoadBalancerInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyRegisterInstancesWithElasticLoadBalancerOutput struct {
	_ struct{} `type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`
}

// String returns the string representation
func (s NiftyRegisterInstancesWithElasticLoadBalancerOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyRegisterInstancesWithElasticLoadBalancer = "NiftyRegisterInstancesWithElasticLoadBalancer"

// NiftyRegisterInstancesWithElasticLoadBalancerRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyRegisterInstancesWithElasticLoadBalancerRequest.
//    req := client.NiftyRegisterInstancesWithElasticLoadBalancerRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/NiftyRegisterInstancesWithElasticLoadBalancer
func (c *Client) NiftyRegisterInstancesWithElasticLoadBalancerRequest(input *NiftyRegisterInstancesWithElasticLoadBalancerInput) NiftyRegisterInstancesWithElasticLoadBalancerRequest {
	op := &aws.Operation{
		Name:       opNiftyRegisterInstancesWithElasticLoadBalancer,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyRegisterInstancesWithElasticLoadBalancerInput{}
	}

	req := c.newRequest(op, input, &NiftyRegisterInstancesWithElasticLoadBalancerOutput{})
	return NiftyRegisterInstancesWithElasticLoadBalancerRequest{Request: req, Input: input, Copy: c.NiftyRegisterInstancesWithElasticLoadBalancerRequest}
}

// NiftyRegisterInstancesWithElasticLoadBalancerRequest is the request type for the
// NiftyRegisterInstancesWithElasticLoadBalancer API operation.
type NiftyRegisterInstancesWithElasticLoadBalancerRequest struct {
	*aws.Request
	Input *NiftyRegisterInstancesWithElasticLoadBalancerInput
	Copy  func(*NiftyRegisterInstancesWithElasticLoadBalancerInput) NiftyRegisterInstancesWithElasticLoadBalancerRequest
}

// Send marshals and sends the NiftyRegisterInstancesWithElasticLoadBalancer API request.
func (r NiftyRegisterInstancesWithElasticLoadBalancerRequest) Send(ctx context.Context) (*NiftyRegisterInstancesWithElasticLoadBalancerResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyRegisterInstancesWithElasticLoadBalancerResponse{
		NiftyRegisterInstancesWithElasticLoadBalancerOutput: r.Request.Data.(*NiftyRegisterInstancesWithElasticLoadBalancerOutput),
		response: &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyRegisterInstancesWithElasticLoadBalancerResponse is the response type for the
// NiftyRegisterInstancesWithElasticLoadBalancer API operation.
type NiftyRegisterInstancesWithElasticLoadBalancerResponse struct {
	*NiftyRegisterInstancesWithElasticLoadBalancerOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyRegisterInstancesWithElasticLoadBalancer request.
func (r *NiftyRegisterInstancesWithElasticLoadBalancerResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
