// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type NiftyModifyElasticLoadBalancerAttributesInput struct {
	_ struct{} `type:"structure"`

	ElasticLoadBalancerId *string `locationName:"ElasticLoadBalancerId" type:"string"`

	ElasticLoadBalancerName *string `locationName:"ElasticLoadBalancerName" type:"string"`

	ElasticLoadBalancerPort *int64 `locationName:"ElasticLoadBalancerPort" type:"integer"`

	InstancePort *int64 `locationName:"InstancePort" type:"integer"`

	LoadBalancerAttributes *RequestLoadBalancerAttributesStruct `locationName:"LoadBalancerAttributes" type:"structure"`

	Protocol *string `locationName:"Protocol" type:"string"`
}

// String returns the string representation
func (s NiftyModifyElasticLoadBalancerAttributesInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyModifyElasticLoadBalancerAttributesOutput struct {
	_ struct{} `type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`
}

// String returns the string representation
func (s NiftyModifyElasticLoadBalancerAttributesOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyModifyElasticLoadBalancerAttributes = "NiftyModifyElasticLoadBalancerAttributes"

// NiftyModifyElasticLoadBalancerAttributesRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyModifyElasticLoadBalancerAttributesRequest.
//    req := client.NiftyModifyElasticLoadBalancerAttributesRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/NiftyModifyElasticLoadBalancerAttributes
func (c *Client) NiftyModifyElasticLoadBalancerAttributesRequest(input *NiftyModifyElasticLoadBalancerAttributesInput) NiftyModifyElasticLoadBalancerAttributesRequest {
	op := &aws.Operation{
		Name:       opNiftyModifyElasticLoadBalancerAttributes,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyModifyElasticLoadBalancerAttributesInput{}
	}

	req := c.newRequest(op, input, &NiftyModifyElasticLoadBalancerAttributesOutput{})
	return NiftyModifyElasticLoadBalancerAttributesRequest{Request: req, Input: input, Copy: c.NiftyModifyElasticLoadBalancerAttributesRequest}
}

// NiftyModifyElasticLoadBalancerAttributesRequest is the request type for the
// NiftyModifyElasticLoadBalancerAttributes API operation.
type NiftyModifyElasticLoadBalancerAttributesRequest struct {
	*aws.Request
	Input *NiftyModifyElasticLoadBalancerAttributesInput
	Copy  func(*NiftyModifyElasticLoadBalancerAttributesInput) NiftyModifyElasticLoadBalancerAttributesRequest
}

// Send marshals and sends the NiftyModifyElasticLoadBalancerAttributes API request.
func (r NiftyModifyElasticLoadBalancerAttributesRequest) Send(ctx context.Context) (*NiftyModifyElasticLoadBalancerAttributesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyModifyElasticLoadBalancerAttributesResponse{
		NiftyModifyElasticLoadBalancerAttributesOutput: r.Request.Data.(*NiftyModifyElasticLoadBalancerAttributesOutput),
		response: &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyModifyElasticLoadBalancerAttributesResponse is the response type for the
// NiftyModifyElasticLoadBalancerAttributes API operation.
type NiftyModifyElasticLoadBalancerAttributesResponse struct {
	*NiftyModifyElasticLoadBalancerAttributesOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyModifyElasticLoadBalancerAttributes request.
func (r *NiftyModifyElasticLoadBalancerAttributesResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
