// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type CreateVpnConnectionInput struct {
	_ struct{} `type:"structure"`

	Agreement *bool `locationName:"Agreement" type:"boolean"`

	CustomerGatewayId *string `locationName:"CustomerGatewayId" type:"string"`

	NiftyCustomerGatewayName *string `locationName:"NiftyCustomerGatewayName" type:"string"`

	NiftyIpsecConfiguration *RequestNiftyIpsecConfigurationStruct `locationName:"NiftyIpsecConfiguration" type:"structure"`

	NiftyTunnel *RequestNiftyTunnelStruct `locationName:"NiftyTunnel" type:"structure"`

	NiftyVpnConnectionDescription *string `locationName:"NiftyVpnConnectionDescription" type:"string"`

	NiftyVpnConnectionMtu *string `locationName:"NiftyVpnConnectionMtu" type:"string"`

	NiftyVpnGatewayName *string `locationName:"NiftyVpnGatewayName" type:"string"`

	Type *string `locationName:"Type" type:"string"`

	VpnGatewayId *string `locationName:"VpnGatewayId" type:"string"`
}

// String returns the string representation
func (s CreateVpnConnectionInput) String() string {
	return nifcloudutil.Prettify(s)
}

type CreateVpnConnectionOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	VpnConnection *VpnConnection `locationName:"vpnConnection" type:"structure"`
}

// String returns the string representation
func (s CreateVpnConnectionOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opCreateVpnConnection = "CreateVpnConnection"

// CreateVpnConnectionRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using CreateVpnConnectionRequest.
//    req := client.CreateVpnConnectionRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/CreateVpnConnection
func (c *Client) CreateVpnConnectionRequest(input *CreateVpnConnectionInput) CreateVpnConnectionRequest {
	op := &aws.Operation{
		Name:       opCreateVpnConnection,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &CreateVpnConnectionInput{}
	}

	req := c.newRequest(op, input, &CreateVpnConnectionOutput{})
	return CreateVpnConnectionRequest{Request: req, Input: input, Copy: c.CreateVpnConnectionRequest}
}

// CreateVpnConnectionRequest is the request type for the
// CreateVpnConnection API operation.
type CreateVpnConnectionRequest struct {
	*aws.Request
	Input *CreateVpnConnectionInput
	Copy  func(*CreateVpnConnectionInput) CreateVpnConnectionRequest
}

// Send marshals and sends the CreateVpnConnection API request.
func (r CreateVpnConnectionRequest) Send(ctx context.Context) (*CreateVpnConnectionResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &CreateVpnConnectionResponse{
		CreateVpnConnectionOutput: r.Request.Data.(*CreateVpnConnectionOutput),
		response:                  &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// CreateVpnConnectionResponse is the response type for the
// CreateVpnConnection API operation.
type CreateVpnConnectionResponse struct {
	*CreateVpnConnectionOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// CreateVpnConnection request.
func (r *CreateVpnConnectionResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
