// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type ModifyImageAttributeInput struct {
	_ struct{} `type:"structure"`

	Attribute *string `locationName:"Attribute" type:"string"`

	ImageId *string `locationName:"ImageId" type:"string"`

	Value *string `locationName:"Value" type:"string"`
}

// String returns the string representation
func (s ModifyImageAttributeInput) String() string {
	return nifcloudutil.Prettify(s)
}

type ModifyImageAttributeOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`
}

// String returns the string representation
func (s ModifyImageAttributeOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opModifyImageAttribute = "ModifyImageAttribute"

// ModifyImageAttributeRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using ModifyImageAttributeRequest.
//    req := client.ModifyImageAttributeRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/ModifyImageAttribute
func (c *Client) ModifyImageAttributeRequest(input *ModifyImageAttributeInput) ModifyImageAttributeRequest {
	op := &aws.Operation{
		Name:       opModifyImageAttribute,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &ModifyImageAttributeInput{}
	}

	req := c.newRequest(op, input, &ModifyImageAttributeOutput{})
	return ModifyImageAttributeRequest{Request: req, Input: input, Copy: c.ModifyImageAttributeRequest}
}

// ModifyImageAttributeRequest is the request type for the
// ModifyImageAttribute API operation.
type ModifyImageAttributeRequest struct {
	*aws.Request
	Input *ModifyImageAttributeInput
	Copy  func(*ModifyImageAttributeInput) ModifyImageAttributeRequest
}

// Send marshals and sends the ModifyImageAttribute API request.
func (r ModifyImageAttributeRequest) Send(ctx context.Context) (*ModifyImageAttributeResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ModifyImageAttributeResponse{
		ModifyImageAttributeOutput: r.Request.Data.(*ModifyImageAttributeOutput),
		response:                   &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ModifyImageAttributeResponse is the response type for the
// ModifyImageAttribute API operation.
type ModifyImageAttributeResponse struct {
	*ModifyImageAttributeOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ModifyImageAttribute request.
func (r *ModifyImageAttributeResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
