// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type DissociateUsersInput struct {
	_ struct{} `type:"structure"`

	FunctionName *string `locationName:"FunctionName" type:"string"`

	Users []RequestUsersStruct `locationName:"Users" locationNameList:"member" type:"list"`
}

// String returns the string representation
func (s DissociateUsersInput) String() string {
	return nifcloudutil.Prettify(s)
}

type DissociateUsersOutput struct {
	_ struct{} `type:"structure"`

	DissociateUsersResult *DissociateUsersResult `locationName:"DissociateUsersResult" type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`

	Users []UsersMemberItem `locationName:"Users" locationNameList:"member" type:"list"`
}

// String returns the string representation
func (s DissociateUsersOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDissociateUsers = "DissociateUsers"

// DissociateUsersRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DissociateUsersRequest.
//    req := client.DissociateUsersRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/DissociateUsers
func (c *Client) DissociateUsersRequest(input *DissociateUsersInput) DissociateUsersRequest {
	op := &aws.Operation{
		Name:       opDissociateUsers,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DissociateUsersInput{}
	}

	req := c.newRequest(op, input, &DissociateUsersOutput{})
	return DissociateUsersRequest{Request: req, Input: input, Copy: c.DissociateUsersRequest}
}

// DissociateUsersRequest is the request type for the
// DissociateUsers API operation.
type DissociateUsersRequest struct {
	*aws.Request
	Input *DissociateUsersInput
	Copy  func(*DissociateUsersInput) DissociateUsersRequest
}

// Send marshals and sends the DissociateUsers API request.
func (r DissociateUsersRequest) Send(ctx context.Context) (*DissociateUsersResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DissociateUsersResponse{
		DissociateUsersOutput: r.Request.Data.(*DissociateUsersOutput),
		response:              &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DissociateUsersResponse is the response type for the
// DissociateUsers API operation.
type DissociateUsersResponse struct {
	*DissociateUsersOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DissociateUsers request.
func (r *DissociateUsersResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
