// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/alice02/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type RunInstancesInput struct {
	_ struct{} `type:"structure"`

	AccountingType *string `locationName:"AccountingType" type:"string"`

	Admin *string `locationName:"Admin" type:"string"`

	Agreement *bool `locationName:"Agreement" type:"boolean"`

	Description *string `locationName:"Description" type:"string"`

	DisableApiTermination *bool `locationName:"DisableApiTermination" type:"boolean"`

	ImageId *string `locationName:"ImageId" type:"string"`

	InstanceId *string `locationName:"InstanceId" type:"string"`

	InstanceType *string `locationName:"InstanceType" type:"string"`

	IpType *string `locationName:"IpType" type:"string"`

	KeyName *string `locationName:"KeyName" type:"string"`

	License []RequestLicenseStruct `locationName:"License" type:"list"`

	NetworkInterface []RequestNetworkInterfaceStruct `locationName:"NetworkInterface" type:"list"`

	Password *string `locationName:"Password" type:"string"`

	Placement *RequestPlacementStruct `locationName:"Placement" type:"structure"`

	PublicIp *string `locationName:"PublicIp" type:"string"`

	SecurityGroup []string `locationName:"SecurityGroup" type:"list"`

	UserData *string `locationName:"UserData" type:"string"`
}

// String returns the string representation
func (s RunInstancesInput) String() string {
	return nifcloudutil.Prettify(s)
}

type RunInstancesOutput struct {
	_ struct{} `type:"structure"`

	GroupSet []GroupSetItem `locationName:"groupSet" locationNameList:"item" type:"list"`

	InstancesSet []InstancesSetItem `locationName:"instancesSet" locationNameList:"item" type:"list"`

	OwnerId *string `locationName:"ownerId" type:"string"`

	RequestId *string `locationName:"requestId" type:"string"`

	RequesterId *string `locationName:"requesterId" type:"string"`

	ReservationId *string `locationName:"reservationId" type:"string"`
}

// String returns the string representation
func (s RunInstancesOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opRunInstances = "RunInstances"

// RunInstancesRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using RunInstancesRequest.
//    req := client.RunInstancesRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/RunInstances
func (c *Client) RunInstancesRequest(input *RunInstancesInput) RunInstancesRequest {
	op := &aws.Operation{
		Name:       opRunInstances,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &RunInstancesInput{}
	}

	req := c.newRequest(op, input, &RunInstancesOutput{})
	return RunInstancesRequest{Request: req, Input: input, Copy: c.RunInstancesRequest}
}

// RunInstancesRequest is the request type for the
// RunInstances API operation.
type RunInstancesRequest struct {
	*aws.Request
	Input *RunInstancesInput
	Copy  func(*RunInstancesInput) RunInstancesRequest
}

// Send marshals and sends the RunInstances API request.
func (r RunInstancesRequest) Send(ctx context.Context) (*RunInstancesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &RunInstancesResponse{
		RunInstancesOutput: r.Request.Data.(*RunInstancesOutput),
		response:           &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// RunInstancesResponse is the response type for the
// RunInstances API operation.
type RunInstancesResponse struct {
	*RunInstancesOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// RunInstances request.
func (r *RunInstancesResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
