// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/alice02/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type NiftyCreateRouterInput struct {
	_ struct{} `type:"structure"`

	AccountingType *string `locationName:"AccountingType" type:"string"`

	AvailabilityZone *string `locationName:"AvailabilityZone" type:"string"`

	Description *string `locationName:"Description" type:"string"`

	NetworkInterface []RequestNetworkInterfaceStruct `locationName:"NetworkInterface" type:"list"`

	RouterName *string `locationName:"RouterName" type:"string"`

	SecurityGroup []string `locationName:"SecurityGroup" type:"list"`

	Type *string `locationName:"Type" type:"string"`
}

// String returns the string representation
func (s NiftyCreateRouterInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyCreateRouterOutput struct {
	_ struct{} `type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	Router *Router `locationName:"router" type:"structure"`
}

// String returns the string representation
func (s NiftyCreateRouterOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyCreateRouter = "NiftyCreateRouter"

// NiftyCreateRouterRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyCreateRouterRequest.
//    req := client.NiftyCreateRouterRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/NiftyCreateRouter
func (c *Client) NiftyCreateRouterRequest(input *NiftyCreateRouterInput) NiftyCreateRouterRequest {
	op := &aws.Operation{
		Name:       opNiftyCreateRouter,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyCreateRouterInput{}
	}

	req := c.newRequest(op, input, &NiftyCreateRouterOutput{})
	return NiftyCreateRouterRequest{Request: req, Input: input, Copy: c.NiftyCreateRouterRequest}
}

// NiftyCreateRouterRequest is the request type for the
// NiftyCreateRouter API operation.
type NiftyCreateRouterRequest struct {
	*aws.Request
	Input *NiftyCreateRouterInput
	Copy  func(*NiftyCreateRouterInput) NiftyCreateRouterRequest
}

// Send marshals and sends the NiftyCreateRouter API request.
func (r NiftyCreateRouterRequest) Send(ctx context.Context) (*NiftyCreateRouterResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyCreateRouterResponse{
		NiftyCreateRouterOutput: r.Request.Data.(*NiftyCreateRouterOutput),
		response:                &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyCreateRouterResponse is the response type for the
// NiftyCreateRouter API operation.
type NiftyCreateRouterResponse struct {
	*NiftyCreateRouterOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyCreateRouter request.
func (r *NiftyCreateRouterResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
