// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type NiftyReplaceElasticLoadBalancerLatestVersionInput struct {
	_ struct{} `type:"structure"`

	ElasticLoadBalancerId *string `locationName:"ElasticLoadBalancerId" type:"string"`

	ElasticLoadBalancerName *string `locationName:"ElasticLoadBalancerName" type:"string"`
}

// String returns the string representation
func (s NiftyReplaceElasticLoadBalancerLatestVersionInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyReplaceElasticLoadBalancerLatestVersionOutput struct {
	_ struct{} `type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`
}

// String returns the string representation
func (s NiftyReplaceElasticLoadBalancerLatestVersionOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyReplaceElasticLoadBalancerLatestVersion = "NiftyReplaceElasticLoadBalancerLatestVersion"

// NiftyReplaceElasticLoadBalancerLatestVersionRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyReplaceElasticLoadBalancerLatestVersionRequest.
//    req := client.NiftyReplaceElasticLoadBalancerLatestVersionRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/NiftyReplaceElasticLoadBalancerLatestVersion
func (c *Client) NiftyReplaceElasticLoadBalancerLatestVersionRequest(input *NiftyReplaceElasticLoadBalancerLatestVersionInput) NiftyReplaceElasticLoadBalancerLatestVersionRequest {
	op := &aws.Operation{
		Name:       opNiftyReplaceElasticLoadBalancerLatestVersion,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyReplaceElasticLoadBalancerLatestVersionInput{}
	}

	req := c.newRequest(op, input, &NiftyReplaceElasticLoadBalancerLatestVersionOutput{})
	return NiftyReplaceElasticLoadBalancerLatestVersionRequest{Request: req, Input: input, Copy: c.NiftyReplaceElasticLoadBalancerLatestVersionRequest}
}

// NiftyReplaceElasticLoadBalancerLatestVersionRequest is the request type for the
// NiftyReplaceElasticLoadBalancerLatestVersion API operation.
type NiftyReplaceElasticLoadBalancerLatestVersionRequest struct {
	*aws.Request
	Input *NiftyReplaceElasticLoadBalancerLatestVersionInput
	Copy  func(*NiftyReplaceElasticLoadBalancerLatestVersionInput) NiftyReplaceElasticLoadBalancerLatestVersionRequest
}

// Send marshals and sends the NiftyReplaceElasticLoadBalancerLatestVersion API request.
func (r NiftyReplaceElasticLoadBalancerLatestVersionRequest) Send(ctx context.Context) (*NiftyReplaceElasticLoadBalancerLatestVersionResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyReplaceElasticLoadBalancerLatestVersionResponse{
		NiftyReplaceElasticLoadBalancerLatestVersionOutput: r.Request.Data.(*NiftyReplaceElasticLoadBalancerLatestVersionOutput),
		response: &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyReplaceElasticLoadBalancerLatestVersionResponse is the response type for the
// NiftyReplaceElasticLoadBalancerLatestVersion API operation.
type NiftyReplaceElasticLoadBalancerLatestVersionResponse struct {
	*NiftyReplaceElasticLoadBalancerLatestVersionOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyReplaceElasticLoadBalancerLatestVersion request.
func (r *NiftyReplaceElasticLoadBalancerLatestVersionResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
