// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type DescribeInstanceAttributeInput struct {
	_ struct{} `type:"structure"`

	Attribute *string `locationName:"Attribute" type:"string"`

	InstanceId *string `locationName:"InstanceId" type:"string"`
}

// String returns the string representation
func (s DescribeInstanceAttributeInput) String() string {
	return nifcloudutil.Prettify(s)
}

type DescribeInstanceAttributeOutput struct {
	_ struct{} `type:"structure"`

	AccountingType *AccountingType `locationName:"accountingType" type:"structure"`

	Autoscaling *Autoscaling `locationName:"autoscaling" type:"structure"`

	BlockDeviceMapping []BlockDeviceMappingSetItem `locationName:"blockDeviceMapping" locationNameList:"item" type:"list"`

	CopyInfo *CopyInfo `locationName:"copyInfo" type:"structure"`

	DescriptionValue *DescriptionValue `locationName:"descriptionValue" type:"structure"`

	DisableApiTermination *DisableApiTermination `locationName:"disableApiTermination" type:"structure"`

	GroupIdValue *GroupIdValue `locationName:"groupIdValue" type:"structure"`

	InstanceId *string `locationName:"instanceId" type:"string"`

	InstanceInitiatedShutdownBehavior *InstanceInitiatedShutdownBehavior `locationName:"instanceInitiatedShutdownBehavior" type:"structure"`

	InstanceType *InstanceType `locationName:"instanceType" type:"structure"`

	InstanceUniqueId *string `locationName:"instanceUniqueId" type:"string"`

	IpType *IpType `locationName:"ipType" type:"structure"`

	Kernel *Kernel `locationName:"kernel" type:"structure"`

	Loadbalancing []LoadbalancingSetItem `locationName:"loadbalancing" locationNameList:"item" type:"list"`

	NetworkInterfaceSet []NetworkInterfaceSetItem `locationName:"networkInterfaceSet" locationNameList:"item" type:"list"`

	NextMonthAccountingType *NextMonthAccountingType `locationName:"NextMonthAccountingType" type:"structure"`

	NiftyElasticLoadBalancing []NiftyElasticLoadBalancingSetItem `locationName:"niftyElasticLoadBalancing" locationNameList:"item" type:"list"`

	NiftyPrivateIpType *NiftyPrivateIpType `locationName:"niftyPrivateIpType" type:"structure"`

	Ramdisk *Ramdisk `locationName:"ramdisk" type:"structure"`

	RequestId *string `locationName:"requestId" type:"string"`

	RootDeviceName *RootDeviceName `locationName:"rootDeviceName" type:"structure"`

	UserData *UserData `locationName:"userData" type:"structure"`
}

// String returns the string representation
func (s DescribeInstanceAttributeOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opDescribeInstanceAttribute = "DescribeInstanceAttribute"

// DescribeInstanceAttributeRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using DescribeInstanceAttributeRequest.
//    req := client.DescribeInstanceAttributeRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/DescribeInstanceAttribute
func (c *Client) DescribeInstanceAttributeRequest(input *DescribeInstanceAttributeInput) DescribeInstanceAttributeRequest {
	op := &aws.Operation{
		Name:       opDescribeInstanceAttribute,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &DescribeInstanceAttributeInput{}
	}

	req := c.newRequest(op, input, &DescribeInstanceAttributeOutput{})
	return DescribeInstanceAttributeRequest{Request: req, Input: input, Copy: c.DescribeInstanceAttributeRequest}
}

// DescribeInstanceAttributeRequest is the request type for the
// DescribeInstanceAttribute API operation.
type DescribeInstanceAttributeRequest struct {
	*aws.Request
	Input *DescribeInstanceAttributeInput
	Copy  func(*DescribeInstanceAttributeInput) DescribeInstanceAttributeRequest
}

// Send marshals and sends the DescribeInstanceAttribute API request.
func (r DescribeInstanceAttributeRequest) Send(ctx context.Context) (*DescribeInstanceAttributeResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &DescribeInstanceAttributeResponse{
		DescribeInstanceAttributeOutput: r.Request.Data.(*DescribeInstanceAttributeOutput),
		response:                        &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// DescribeInstanceAttributeResponse is the response type for the
// DescribeInstanceAttribute API operation.
type DescribeInstanceAttributeResponse struct {
	*DescribeInstanceAttributeOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// DescribeInstanceAttribute request.
func (r *DescribeInstanceAttributeResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
