// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type ImportInstanceInput struct {
	_ struct{} `type:"structure"`

	AccountingType *string `locationName:"AccountingType" type:"string"`

	Description *string `locationName:"Description" type:"string"`

	InstanceId *string `locationName:"InstanceId" type:"string"`

	InstanceType *string `locationName:"InstanceType" type:"string"`

	IpType *string `locationName:"IpType" type:"string"`

	NetworkInterface []RequestNetworkInterfaceStruct `locationName:"NetworkInterface" type:"list"`

	Ovf *string `locationName:"Ovf" type:"string"`

	Placement *RequestPlacementStruct `locationName:"Placement" type:"structure"`

	PublicIp *string `locationName:"PublicIp" type:"string"`

	SecurityGroup []string `locationName:"SecurityGroup" type:"list"`
}

// String returns the string representation
func (s ImportInstanceInput) String() string {
	return nifcloudutil.Prettify(s)
}

type ImportInstanceOutput struct {
	_ struct{} `type:"structure"`

	ConversionTask *ConversionTask `locationName:"conversionTask" type:"structure"`
}

// String returns the string representation
func (s ImportInstanceOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opImportInstance = "ImportInstance"

// ImportInstanceRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using ImportInstanceRequest.
//    req := client.ImportInstanceRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/ImportInstance
func (c *Client) ImportInstanceRequest(input *ImportInstanceInput) ImportInstanceRequest {
	op := &aws.Operation{
		Name:       opImportInstance,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &ImportInstanceInput{}
	}

	req := c.newRequest(op, input, &ImportInstanceOutput{})
	return ImportInstanceRequest{Request: req, Input: input, Copy: c.ImportInstanceRequest}
}

// ImportInstanceRequest is the request type for the
// ImportInstance API operation.
type ImportInstanceRequest struct {
	*aws.Request
	Input *ImportInstanceInput
	Copy  func(*ImportInstanceInput) ImportInstanceRequest
}

// Send marshals and sends the ImportInstance API request.
func (r ImportInstanceRequest) Send(ctx context.Context) (*ImportInstanceResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ImportInstanceResponse{
		ImportInstanceOutput: r.Request.Data.(*ImportInstanceOutput),
		response:             &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ImportInstanceResponse is the response type for the
// ImportInstance API operation.
type ImportInstanceResponse struct {
	*ImportInstanceOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ImportInstance request.
func (r *ImportInstanceResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
