// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package computing

import (
	"context"

	"github.com/aokumasan/nifcloud-sdk-go-v2/internal/nifcloudutil"
	"github.com/aws/aws-sdk-go-v2/aws"
)

type NiftyDescribeInstanceElasticLoadBalancerHealthInput struct {
	_ struct{} `type:"structure"`

	ElasticLoadBalancerId *string `locationName:"ElasticLoadBalancerId" type:"string"`

	ElasticLoadBalancerName *string `locationName:"ElasticLoadBalancerName" type:"string"`

	ElasticLoadBalancerPort *int64 `locationName:"ElasticLoadBalancerPort" type:"integer"`

	InstancePort *int64 `locationName:"InstancePort" type:"integer"`

	Instances []RequestInstancesStruct `locationName:"Instances" locationNameList:"member" type:"list"`

	Protocol *string `locationName:"Protocol" type:"string"`
}

// String returns the string representation
func (s NiftyDescribeInstanceElasticLoadBalancerHealthInput) String() string {
	return nifcloudutil.Prettify(s)
}

type NiftyDescribeInstanceElasticLoadBalancerHealthOutput struct {
	_ struct{} `type:"structure"`

	InstanceStates []InstanceStatesMemberItem `locationName:"InstanceStates" locationNameList:"member" type:"list"`

	NiftyDescribeInstanceElasticLoadBalancerHealthResult *NiftyDescribeInstanceElasticLoadBalancerHealthResult `locationName:"NiftyDescribeInstanceElasticLoadBalancerHealthResult" type:"structure"`

	ResponseMetadata *ResponseMetadata `locationName:"ResponseMetadata" type:"structure"`
}

// String returns the string representation
func (s NiftyDescribeInstanceElasticLoadBalancerHealthOutput) String() string {
	return nifcloudutil.Prettify(s)
}

const opNiftyDescribeInstanceElasticLoadBalancerHealth = "NiftyDescribeInstanceElasticLoadBalancerHealth"

// NiftyDescribeInstanceElasticLoadBalancerHealthRequest returns a request value for making API operation for
// NIFCLOUD Computing.
//
//    // Example sending a request using NiftyDescribeInstanceElasticLoadBalancerHealthRequest.
//    req := client.NiftyDescribeInstanceElasticLoadBalancerHealthRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/computing-2016-11-15/NiftyDescribeInstanceElasticLoadBalancerHealth
func (c *Client) NiftyDescribeInstanceElasticLoadBalancerHealthRequest(input *NiftyDescribeInstanceElasticLoadBalancerHealthInput) NiftyDescribeInstanceElasticLoadBalancerHealthRequest {
	op := &aws.Operation{
		Name:       opNiftyDescribeInstanceElasticLoadBalancerHealth,
		HTTPMethod: "POST",
		HTTPPath:   "/api/",
	}

	if input == nil {
		input = &NiftyDescribeInstanceElasticLoadBalancerHealthInput{}
	}

	req := c.newRequest(op, input, &NiftyDescribeInstanceElasticLoadBalancerHealthOutput{})
	return NiftyDescribeInstanceElasticLoadBalancerHealthRequest{Request: req, Input: input, Copy: c.NiftyDescribeInstanceElasticLoadBalancerHealthRequest}
}

// NiftyDescribeInstanceElasticLoadBalancerHealthRequest is the request type for the
// NiftyDescribeInstanceElasticLoadBalancerHealth API operation.
type NiftyDescribeInstanceElasticLoadBalancerHealthRequest struct {
	*aws.Request
	Input *NiftyDescribeInstanceElasticLoadBalancerHealthInput
	Copy  func(*NiftyDescribeInstanceElasticLoadBalancerHealthInput) NiftyDescribeInstanceElasticLoadBalancerHealthRequest
}

// Send marshals and sends the NiftyDescribeInstanceElasticLoadBalancerHealth API request.
func (r NiftyDescribeInstanceElasticLoadBalancerHealthRequest) Send(ctx context.Context) (*NiftyDescribeInstanceElasticLoadBalancerHealthResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &NiftyDescribeInstanceElasticLoadBalancerHealthResponse{
		NiftyDescribeInstanceElasticLoadBalancerHealthOutput: r.Request.Data.(*NiftyDescribeInstanceElasticLoadBalancerHealthOutput),
		response: &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// NiftyDescribeInstanceElasticLoadBalancerHealthResponse is the response type for the
// NiftyDescribeInstanceElasticLoadBalancerHealth API operation.
type NiftyDescribeInstanceElasticLoadBalancerHealthResponse struct {
	*NiftyDescribeInstanceElasticLoadBalancerHealthOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// NiftyDescribeInstanceElasticLoadBalancerHealth request.
func (r *NiftyDescribeInstanceElasticLoadBalancerHealthResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
